# Generated by Django 6.0.4 on 2026-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='weighht',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
