# Generated by Django 6.0.4 on 2026-04-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_viewer', '0002_rename_weighht_dataentry_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='payload_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
